### ISSUE TITLE
브론즈5 1271번

### ISSUE THREAD

**Issue by ghost** [BOJ-expedition/Challenges-of-the-week#1]
입력
첫째 줄에는 최백준 조교가 가진 돈 n과 돈을 받으러 온 생명체의 수 m이 주어진다. (1 ≤ m ≤ n ≤ 101000, m과 n은 10진수 정수)

출력
첫째 줄에 생명체 하나에게 돌아가는 돈의 양을 출력한다. 그리고 두 번째 줄에는 1원씩 분배할 수 없는 남는 돈을 출력한다.

이하 소스 코드
사용 언어 node.js

const fs = require('fs'); // 파일시스템 모듈
const arr = fs.readFileSync('/dev/stdin').toString().split(' '); //백준 인풋 파일 설정
const max = Math.floor(+arr[0] / +arr[1]); 
const extra = +arr[0] % +max; // 나머지값
console.log(max + '\n' + extra); // 출력

////

첨엔 스위프트로 해보려다가 문법이 많이 낯설어서 쓰기 쉬운 js로 넘어왔는데

브론즈5라고 얕봤는데 졸면서 하다가 이것조차도 못푸는 게 화딱지가 나서 고양이 찍는 문제 풀었음.

<img width="1106" alt="스크린샷 2020-12-29 오전 12 39 28" src="https://user-images.githubusercontent.com/76655411/103225964-6f737580-496e-11eb-9cca-a2321f61c425.png">

**Comment by naldal** [comment]
새로운 언어쓰면 다 글치뭐

**Comment by yurihan** [comment]
https://www.acmicpc.net/problem/1271

일반적인 언어면 그냥 풀 경우에 오버플로우 나서 결과 안나옴.
