### ISSUE TITLE
무식하게 푼 문제가 하나 있는데 유식하게 풀 수 있는 방법이 있을까?

### ISSUE THREAD

**Issue by ghost** [BOJ-expedition/Challenges-of-the-week#14]
https://www.acmicpc.net/problem/2231

정수 N이 주어졌을 때 N과 N의 각 자리수들의 합을 분해합이라고 하는데 (분해해서->합한다)

이 분해합을 만들 수 있는 정수 N을 분해합의 생성자라고 한다고 함.

예를 들어 ( 123 => 123+1+2+3 => 129 ) 에서 123은 129의 생성자이고 129는 123의 분해합임.

그리고 어떤 분해합에 대해 여러개의 생성자가 있을 수 있는데

문제는 어떤 분해합의 최소 생성자를 찾는 것

    const NtoM = (N:number) : number=>{
        const num : number = N;
        const arr:number[] = N.toString().split("").map(elem=>+elem);

        let M = 0;
        for(let i=0; i<arr.length; i++){
           M += arr[i];
        }

        return M+num;
    }

    const MtoN = (M:number) : number => {
        let NArr:number[] = M.toString().split("").map(elem=>+elem);
        let firstValue;

        if ( NArr[0]-1 > 0 )
            firstValue = (NArr[0]-1) * Math.pow(10, NArr.length-1);
        else
            firstValue = 9 * Math.pow(10, NArr.length-2);

        let N = 0;
        for(let n=firstValue; n<M; n++){
            const Nv=NtoM(n)
            if(Nv === M){
                N = n;
                break;
            }
        }

        return N;
    }

이런 식으로 해서 어떤 분해합이 주어졌을 때 분해합의 가장 큰 자리의 값을 -1만큼 빼서(100이면 90, 200이면 100) 
거기서부터 반복문 돌려서 찾게 했는데
정답은 처리가 됐는데 더 좋은 아이디어가 있을까 싶어서...
백준은 효율성 이런 건 점수를 안쳐주다보니 여쭤봅니다

**Comment by yurihan** [comment]
N(1 ≤ N ≤ 1,000,000) 이니까 그냥 최대값 1,000,000 이라고 치면
최대 자릿수만큼 9로 채워져있을때 9*7 = 63 밖에 안됨.
999,937을 미니멈으로 두고 여기서부터 생성자를 찾으면 좀 빠르긴 할거임.

**Comment by ghost** [comment]
ㅇㅎ... 인풋값 범위가 괜히 주어지는 게 아니군...
약간 방정식처럼 풀어보고 싶었는데 접근법은 이게 ㄱㅊ은 것인가요?

**Comment by yurihan** [comment]
이 문제는 일반항이 없는 brute force 문제였던걸로 기억함,

**Comment by ghost** [comment]
감사합니다 🙏
