### ISSUE TITLE
스터디 횐님덜.... 도와주세요...

### ISSUE THREAD

**Issue by ghost** [BOJ-expedition/Challenges-of-the-week#15]
https://www.acmicpc.net/problem/1018

8*8의 체스판을 만들어야 하는 문제

일단 무식하게라도 풀고 싶어서
원본 행렬을 각 지점에서 8*8만큼 순회하면서
처음 지점의 좌표의 합이 짝수면 앞으로의 짝수지점은 전부 처음 지점의 값과 같아야 한다 라는 생각으로 함수를 만들었음.

예를 들어 원본 행렬이 아래와 같다고 하고
WBWBWB
WBWBWB
WBWBWB
WBWBWB
WBWBWB
간소화한 예를 들기 위해 4*4의 체스판을 만든다고 할때 [0,0]에서 순회를 시작하면
[0,0]에서 0+0 %2 => 0 이므로 앞으로 x+y가 짝수인 애들은 전부 W이어야함.  또 x+y가 홀수인 애들은 B이어야함.
[0,1]에서 0+1 %2  => 1 이므로 앞으로 x+y가 홀수인 애들은 전부 B이어야함. 또 x+y가 짝수인 애들은 W이어야함.

이런 함수를 하나 짰음

다바꾼다쳐도 8*8을 만들때는 최댓값이 64이므로 기본값으로 65를 줬음

자꾸 오답뜨는데 원인을 못찾겟음...

이하 소스코드

    import fs = require("fs");
    const input:string[] =  fs.readFileSync("/dev/stdin").toString().trim().split("\n").map(elem=>elem.trim());
    const getWrongCntFrom = (y:number, x:number) => {
        const startValue = board[y][x];
        const isOdd = (y+x)%2;

        let cnt = 0;

        for(let i=y; i<y+8; i++){

            for(let j=x; j<x+8; j++){

                if( (i+j)%2 === isOdd){
                    if(board[i][j] !== startValue) cnt++;
                }
                else{
                    if(board[i][j] === startValue) cnt++;
                }
            }

        }

        return cnt;
    }

    const [yLength, xLength] : number[] = input.shift().split(" ").map(elem=>+elem);
    const board : string[][] = input.map( elem=>elem.split(""));

    let minCnt:number = 65;

    for(let y=0; y<yLength-7; y++){
        for(let x=0; x<xLength-7; x++){
            let wrongCountNow = getWrongCntFrom(y,x);
            minCnt = Math.min(minCnt, wrongCountNow);
        }
    }

    console.log(minCnt);

**Comment by yurihan** [comment]
이거 그냥 일차원 배열로 쭉 연결해서 w랑 b 갯수 카운트 해서 지지고 볶아봐.
w랑 b 갯수는 동일하거나(전체짝수) 한쪽이 한개가 더 많으면(전체홀수) 되자너. 
여기서부터 생각해보셈. 
아니네 이렇게 하면 좆되네

**Comment by yurihan** [comment]
마찬가지로 그냥 일차원배열로 생각해서 WB로 번갈아서 체크. 다른놈만 카운트. 
다른놈 또는 전체갯수-다른놈 중 작은놈 리턴.

**Comment by ghost** [comment]
아... 제가 생각을 잘못한 게
지금 짠 거는 처음건 픽스한 뒤로 다음 애들을 어떻게 고칠지 결정하는 거였는데 생각해보니
WWBWBWBW
WBWBWBWB
BWBWBWBW
WBWBWBWB
BWBWBWBW
WBWBWBWB
BWBWBWBW
WBWBWBWB
에서처럼 처음걸 바꿔버리는 게 최소값인 경우도 있었네요...
해결했습니다 감사합니다!
