### ISSUE TITLE
지정문제 순위검색 푸신 분??

### ISSUE THREAD

**Issue by ghost** [BOJ-expedition/Challenges-of-the-week#16]
정확성은 넘어갔는데 효율성에서 떨어지네

효율성도 시간초과가 나오는 거 보면

인포를 미리 어떻게 잘게 쪼개놓고 쿼리에 맞춰서 바로바로 접근해야할 거 같은데

어떤 아이디어가 필요할까 흠..

    function solution(info, query) {
        const table = info.map( string=>{
            const eachInformation = string.split(" ");
            return {
                lang : eachInformation[0],
                area : eachInformation[1],
                level: eachInformation[2],
                food : eachInformation[3],
                score: eachInformation[4]
            };
        });

        const queryString = query.map(
            elem => {
                const array = elem.split(" ").filter(string=>string != "and");
                return {
                    lang : array[0],
                    area : array[1],
                    level: array[2],
                    food : array[3],
                    score: array[4]
                }
            }
        )

        let ret = [];
        for (const finder of queryString) {
            let count = 0;

            for(const row of table){
                
                if( ( finder.lang === "-" || finder.lang === row.lang )
                &&  ( finder.area === "-" || finder.area === row.area )
                &&  ( finder.level=== "-" || finder.level=== row.level )
                &&  ( finder.food === "-" || finder.food === row.food )
                &&  ( finder.score=== "-" || +finder.score <= +row.score )
                ) count++;
            }

            ret.push(count);
        }
        return ret;
    }

**Comment by yurihan** [comment]
필터를 걸어서 조건마다 숫자를 줄이는게 정석일 것 같은데..
더 빡세게는 인덱스까지 만들어두는거고..

**Comment by ghost** [comment]
효율성 검사 2개는 넘어갔는데 2개를 못넘어갔네요 ㅋㅋ 일단 닫습니다... 좀 더 공부하겟습니다
