### ISSUE TITLE
백준 10809 반례찾기좀 도와주세요

### ISSUE THREAD

**Issue by naldal** [BOJ-expedition/Challenges-of-the-week#5]
https://www.acmicpc.net/problem/10809

<img width="922" alt="스크린샷 2021-01-02 오후 3 36 40" src="https://user-images.githubusercontent.com/45508297/103452222-5113ce00-4d10-11eb-9c3f-1f58de958914.png">

```java

import java.io.*;
import java.util.*;

public class Main {
    public static void main(String args[]) throws IOException {
        BufferedReader br = new BufferedReader(new InputStreamReader(System.in));
        BufferedWriter bw = new BufferedWriter(new OutputStreamWriter(System.out));
        StringBuilder sb = new StringBuilder();
        String context = br.readLine().trim();
        int[] alpha = new int[26];
        Arrays.fill(alpha, -1);
        int cnt = 0;
        int[] context_arr = new int[context.length()];
        int tmp = -1;
        for(int i=0; i<context.length(); i++) {
            context_arr[i] = context.charAt(i)-97;
            if (context_arr[i] == tmp) {
                alpha[context_arr[i]] = alpha[context_arr[i]];
            } else {
                alpha[context_arr[i]] = cnt;
            }
            tmp = context_arr[i];
            cnt ++;
        }
        for (int n : alpha) {
            sb.append(n+" ");
        }
        bw.write(sb.toString().trim());
        bw.flush();
        bw.close();
        br.close();
    }
}

```

<img width="640" alt="스크린샷 2021-01-02 오후 3 37 31" src="https://user-images.githubusercontent.com/45508297/103452232-6f79c980-4d10-11eb-9863-ad5280b79aa9.png">

<img width="645" alt="스크린샷 2021-01-02 오후 3 38 03" src="https://user-images.githubusercontent.com/45508297/103452238-828c9980-4d10-11eb-8c46-691359e7b8c2.png">

<img width="821" alt="스크린샷 2021-01-02 오후 3 38 25" src="https://user-images.githubusercontent.com/45508297/103452256-a4861c00-4d10-11eb-8b42-69da50a7e5d1.png">

분명히 잘 푼거같은데 계속 틀렸다고 나오네요;;;

뭐가문제일까요..

**Comment by yurihan** [comment]
뭐야 왜이렇게 복잡하게 짜놨어

**Comment by naldal** [comment]
주석달아서 다시 올려놓겟습니당

**Comment by yurihan** [comment]
tmp는 왜 있냐..
코드 눈으로 대충 보니 abbba 하면 결과 이상하겠는데 ㅎ

**Comment by naldal** [comment]
헐 어케아심 ㄷㄷㄷㄷㄷㄷㄷ

**Comment by yurihan** [comment]
그냥 alpha[context_arr[i]] 가 -1이 아니면 cnt로 셋하면 될 것 같은데 직전 데이터를 tmp에 넣고 지지고볶고있는게 눈에 선해서..

**Comment by naldal** [comment]
헐 ㅋㅋ abbba 보자마자 -1 아닐때만 넣는걸로 고쳤더니 통과했어요
감사합니다!!


이슈닫습니다 :)
