### ISSUE TITLE
도움!!! 백준 1157번

### ISSUE THREAD

**Issue by ghost** [BOJ-expedition/Challenges-of-the-week#7]
Link : https://www.acmicpc.net/problem/1157
Input : 첫째 줄에 알파벳 대소문자로 이루어진 단어가 주어진다. 주어지는 단어의 길이는 1,000,000을 넘지 않는다.
Output : 첫째 줄에 이 단어에서 가장 많이 사용된 알파벳을 대문자로 출력한다. 단, 가장 많이 사용된 알파벳이 여러 개 존재하는 경우에는 ?를 출력한다.

    const fs = require("fs");
    const input = fs.readFileSync("/dev/stdin").toString();
    const txt = input.toUpperCase();
    const set = [...new Set(txt)];
    let result = "?";
    let compareNumber = 0;
    for(let i=0; i<set.length; i++){
        const char = set[i];

        let num = 0;

        for(let j=0; j<txt.length; j++){
            if(txt[j] === char)num++;
        }

        if(num>compareNumber){
            result = char;
            compareNumber = num;
        }
        else if(num===compareNumber){
            result = "?";
        }

    }
    console.log(result);

이게 보통 백준에서 틀리면 100프로 되기 전에 브레이크 걸리면서 틀렸습니다가 나오는데
100프로 됐는데 틀렸다고 나오는데 반례가 생각이 안남
도와주세요...

<img width="1193" alt="스크린샷 2021-01-02 오후 10 52 46" src="https://user-images.githubusercontent.com/76655411/103458838-25640880-4d4f-11eb-9255-fb8ca39780d7.png">

**Comment by naldal** [comment]
갯수를 세어야하는데 Set을 걸면안되지 않을까요?

**Comment by ghost** [comment]
요게 set을 건 게 해당 스트링에서 사용된 유니크한 캐릭터들을 모아서 얘네들만 카운팅하려는 거엿음.
"aabbcc" => set{a,b,c} => [...set{a,b,c}] ( == [a,b,c]  )
이렇게 해서 유니크한 캐릭터들만 모아놓고 반복문으로 각자 카운팅하려는 거엿는데
뭐가 문제지...

**Comment by naldal** [comment]
compareNum이 num 보다 클 가능성은 없나요?

**Comment by naldal** [comment]
abbc확인

**Comment by ghost** [comment]
Comparenum이 num보다 크면 aaabb에서처럼 a의 갯수가 b보다 크기 때문에 그냥 넘어가게 햇음

**Comment by naldal** [comment]
@yurihan 헬프!

**Comment by yurihan** [comment]
이건 그냥 해시맵으로 +1 한 다음에 튜플로 바꿔서 소팅하고 첫번째랑 두번째 비교하면 끝나.

**Comment by naldal** [comment]
저두 해시맵으로 풀었는데 저것두 가능한 풀이아닌가용? 왜 안되지 ㄷㄷ

**Comment by yurihan** [comment]
예전에 풀었던건데 그냥 문자열 자체를 소팅하는 방법도 있음. 
```swift
let input = readLine()!
var lastChar = Character(".")
var count = 0
var charCount:[(char:Character,count:Int)] = []
input.uppercased().sorted().forEach{
    if lastChar != $0 {
        charCount.append((lastChar,count))
        lastChar = $0
        count = 0
    }
    count += 1
}
charCount.append((lastChar,count))
charCount.sort{$0.1 > $1.1}

if charCount[0].count == charCount[1].count
{
    print("?")
}
else
{
    print(charCount[0].char)
}
```

**Comment by yurihan** [comment]
당연히 가능한데 아무래도 건수 늘어나면 효율은 좀 떨어질듯.

**Comment by ghost** [comment]
ㄱㅅㄱㅅㄱㅅㄱㅅㄱㅅㄱㅅ 풀었습니다.
로직을 아예 바꿧는데도 안되길래 먼가 싶어서 인풋에 트림 걸어봣는데 됨 ㅋㅋ
인풋값에 오류가 잇는듯...
